from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthRegisterPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, user_id=None):  # noqa: E501
        """AuthRegisterPost200Response - a model defined in OpenAPI

        :param message: The message of this AuthRegisterPost200Response.  # noqa: E501
        :type message: str
        :param user_id: The user_id of this AuthRegisterPost200Response.  # noqa: E501
        :type user_id: int
        """
        self.openapi_types = {
            'message': str,
            'user_id': int
        }

        self.attribute_map = {
            'message': 'message',
            'user_id': 'user_id'
        }

        self._message = message
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'AuthRegisterPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_register_post_200_response of this AuthRegisterPost200Response.  # noqa: E501
        :rtype: AuthRegisterPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this AuthRegisterPost200Response.


        :return: The message of this AuthRegisterPost200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this AuthRegisterPost200Response.


        :param message: The message of this AuthRegisterPost200Response.
        :type message: str
        """

        self._message = message

    @property
    def user_id(self) -> int:
        """Gets the user_id of this AuthRegisterPost200Response.


        :return: The user_id of this AuthRegisterPost200Response.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this AuthRegisterPost200Response.


        :param user_id: The user_id of this AuthRegisterPost200Response.
        :type user_id: int
        """

        self._user_id = user_id
