from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TreesPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lng=None, type=None):  # noqa: E501
        """TreesPostRequest - a model defined in OpenAPI

        :param lat: The lat of this TreesPostRequest.  # noqa: E501
        :type lat: float
        :param lng: The lng of this TreesPostRequest.  # noqa: E501
        :type lng: float
        :param type: The type of this TreesPostRequest.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'lat': float,
            'lng': float,
            'type': str
        }

        self.attribute_map = {
            'lat': 'lat',
            'lng': 'lng',
            'type': 'type'
        }

        self._lat = lat
        self._lng = lng
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'TreesPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _trees_post_request of this TreesPostRequest.  # noqa: E501
        :rtype: TreesPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this TreesPostRequest.


        :return: The lat of this TreesPostRequest.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this TreesPostRequest.


        :param lat: The lat of this TreesPostRequest.
        :type lat: float
        """

        self._lat = lat

    @property
    def lng(self) -> float:
        """Gets the lng of this TreesPostRequest.


        :return: The lng of this TreesPostRequest.
        :rtype: float
        """
        return self._lng

    @lng.setter
    def lng(self, lng: float):
        """Sets the lng of this TreesPostRequest.


        :param lng: The lng of this TreesPostRequest.
        :type lng: float
        """

        self._lng = lng

    @property
    def type(self) -> str:
        """Gets the type of this TreesPostRequest.


        :return: The type of this TreesPostRequest.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TreesPostRequest.


        :param type: The type of this TreesPostRequest.
        :type type: str
        """

        self._type = type
