from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TreesTreeIdWorklogsPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _date=None, description=None):  # noqa: E501
        """TreesTreeIdWorklogsPostRequest - a model defined in OpenAPI

        :param _date: The _date of this TreesTreeIdWorklogsPostRequest.  # noqa: E501
        :type _date: date
        :param description: The description of this TreesTreeIdWorklogsPostRequest.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            '_date': date,
            'description': str
        }

        self.attribute_map = {
            '_date': 'date',
            'description': 'description'
        }

        self.__date = _date
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TreesTreeIdWorklogsPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _trees__tree_id__worklogs_post_request of this TreesTreeIdWorklogsPostRequest.  # noqa: E501
        :rtype: TreesTreeIdWorklogsPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this TreesTreeIdWorklogsPostRequest.


        :return: The _date of this TreesTreeIdWorklogsPostRequest.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this TreesTreeIdWorklogsPostRequest.


        :param _date: The _date of this TreesTreeIdWorklogsPostRequest.
        :type _date: date
        """

        self.__date = _date

    @property
    def description(self) -> str:
        """Gets the description of this TreesTreeIdWorklogsPostRequest.


        :return: The description of this TreesTreeIdWorklogsPostRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TreesTreeIdWorklogsPostRequest.


        :param description: The description of this TreesTreeIdWorklogsPostRequest.
        :type description: str
        """

        self._description = description
