from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TreesTreeIdLidarPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, lidar_url=None, size_bytes=None, content_type=None, uploaded_at=None):  # noqa: E501
        """TreesTreeIdLidarPost201Response - a model defined in OpenAPI

        :param message: The message of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :type message: str
        :param lidar_url: The lidar_url of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :type lidar_url: str
        :param size_bytes: The size_bytes of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :type size_bytes: int
        :param content_type: The content_type of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :type content_type: str
        :param uploaded_at: The uploaded_at of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :type uploaded_at: datetime
        """
        self.openapi_types = {
            'message': str,
            'lidar_url': str,
            'size_bytes': int,
            'content_type': str,
            'uploaded_at': datetime
        }

        self.attribute_map = {
            'message': 'message',
            'lidar_url': 'lidar_url',
            'size_bytes': 'size_bytes',
            'content_type': 'content_type',
            'uploaded_at': 'uploaded_at'
        }

        self._message = message
        self._lidar_url = lidar_url
        self._size_bytes = size_bytes
        self._content_type = content_type
        self._uploaded_at = uploaded_at

    @classmethod
    def from_dict(cls, dikt) -> 'TreesTreeIdLidarPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _trees__tree_id__lidar_post_201_response of this TreesTreeIdLidarPost201Response.  # noqa: E501
        :rtype: TreesTreeIdLidarPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this TreesTreeIdLidarPost201Response.


        :return: The message of this TreesTreeIdLidarPost201Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this TreesTreeIdLidarPost201Response.


        :param message: The message of this TreesTreeIdLidarPost201Response.
        :type message: str
        """

        self._message = message

    @property
    def lidar_url(self) -> str:
        """Gets the lidar_url of this TreesTreeIdLidarPost201Response.


        :return: The lidar_url of this TreesTreeIdLidarPost201Response.
        :rtype: str
        """
        return self._lidar_url

    @lidar_url.setter
    def lidar_url(self, lidar_url: str):
        """Sets the lidar_url of this TreesTreeIdLidarPost201Response.


        :param lidar_url: The lidar_url of this TreesTreeIdLidarPost201Response.
        :type lidar_url: str
        """

        self._lidar_url = lidar_url

    @property
    def size_bytes(self) -> int:
        """Gets the size_bytes of this TreesTreeIdLidarPost201Response.


        :return: The size_bytes of this TreesTreeIdLidarPost201Response.
        :rtype: int
        """
        return self._size_bytes

    @size_bytes.setter
    def size_bytes(self, size_bytes: int):
        """Sets the size_bytes of this TreesTreeIdLidarPost201Response.


        :param size_bytes: The size_bytes of this TreesTreeIdLidarPost201Response.
        :type size_bytes: int
        """

        self._size_bytes = size_bytes

    @property
    def content_type(self) -> str:
        """Gets the content_type of this TreesTreeIdLidarPost201Response.


        :return: The content_type of this TreesTreeIdLidarPost201Response.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type: str):
        """Sets the content_type of this TreesTreeIdLidarPost201Response.


        :param content_type: The content_type of this TreesTreeIdLidarPost201Response.
        :type content_type: str
        """

        self._content_type = content_type

    @property
    def uploaded_at(self) -> datetime:
        """Gets the uploaded_at of this TreesTreeIdLidarPost201Response.


        :return: The uploaded_at of this TreesTreeIdLidarPost201Response.
        :rtype: datetime
        """
        return self._uploaded_at

    @uploaded_at.setter
    def uploaded_at(self, uploaded_at: datetime):
        """Sets the uploaded_at of this TreesTreeIdLidarPost201Response.


        :param uploaded_at: The uploaded_at of this TreesTreeIdLidarPost201Response.
        :type uploaded_at: datetime
        """

        self._uploaded_at = uploaded_at
